### ISSUE TITLE
Разделить ответы сервера по времени суток

### ISSUE THREAD

**Issue by wired-R** [go-train/server#5]

**Comment by wired-R** [comment]
@oleckin Давай условия и распиание.

**Comment by oleckin** [comment]
*Необходимо учитывать часовой пояс на клиенте
*Подумать, что можно сделать, если на клиенте часовой пояс настроен неверно (например, на клиенте часовой пояс выбрать неверно, но время выставлено "текущее")

- 06:00:01-11:00:00   отвечаем сообщениями из набора "Доброе утро"
- 11:00:01-16:00:00  отвечаем сообщениями из набора "Добрый день"
- 16:00:01-21:00:00 отвечаем сообщениями из набора "Добрый вечер"
- 21:00:01-23:00:00 отвечаем сообщениями из набора "Спокойной ночи"
- 23:00:01-06:00:00 отвечаем сообщениями из набора "Какого хрена ты не спишь"

**Comment by oleckin** [comment]
видимо, никак) остаётся полагаться либо на время на клиенте, либо определять геолокацию клиента и брать часовой пояс определённой локации
можем определять геолокацию?

**Comment by oleckin** [comment]
можно попробовать так:
- если удаётся получить таймзону по геолокации, то используем её
- если нет, то используем таймзону на клиенте

**Comment by wired-R** [comment]
> можем определять геолокацию?
В принципе, можно прикрутить, например, по ip.... но так ли это нужно?

**Comment by oleckin** [comment]
давай прикрутим, может пригодиться)

**Comment by oleckin** [comment]
Подумала ещё раз. В рамках текущей задачи действительно не нужна информация о таймзоне на клиенте.

Тогда так:

*Смотрим на текущее время на клиенте*

- 06:00:01-11:00:00 отвечаем сообщениями из набора "Доброе утро"
- 11:00:01-16:00:00 отвечаем сообщениями из набора "Добрый день"
- 16:00:01-21:00:00 отвечаем сообщениями из набора "Добрый вечер"
- 21:00:01-23:00:00 отвечаем сообщениями из набора "Спокойной ночи"
- 23:00:01-06:00:00 отвечаем сообщениями из набора "Какого хрена ты не спишь"

У меня ещё вопрос - будем рассматривать кейсы с разным форматом времени (am/pm и тд)?

**Comment by wired-R** [comment]
>У меня ещё вопрос - будем рассматривать кейсы с разным форматом времени (am/pm и тд)?


а зачем? буду брать таймштамп и не важно, что там клиент у себя отображает.

**Comment by oleckin** [comment]
ок)

**Comment by wired-R** [comment]
после #6
